---
# yaml-language-server: $schema=https://raw.githubusercontent.com/mfontanini/presenterm/master/config-file-schema.json
defaults:
  # the theme to use by default in every presentation unless overridden.
  theme: dark

options:
  # whether slides are automatically terminated when a slide title is found.
  implicit_slide_ends: true

  # the prefix to use for commands.
  command_prefix: ""

  # show all lists incrementally, by implicitly adding pauses in between elements.
  incremental_lists: true

  # this option tells presenterm you don't care about extra parameters in
  # presentation's front matter. This can be useful if you're trying to load a
  # presentation made for another tool
  strict_front_matter_parsing: true

  # whether to treat a thematic break as a slide end.
  end_slide_shorthand: false

  list_item_newlines: 2


snippet:
  exec:
    # enable code snippet execution. Use at your own risk!
    enable: true

  exec_replace:
    # enable code snippet automatic execution + replacing the snippet with its output. Use at your own risk!
    enable: true

  render:
    # the number of threads to use when rendering `+render` code snippets.
    threads: 2

transition:
  # how long the transition should last.
  duration_millis: 750

  # how many frames should be rendered during the transition
  frames: 45

  # the animation to use
  animation:
    style: collapse_horizontal


